"""Numerically safe supervised and consistency losses."""

from .disparity import (
    charbonnier,
    disparity_loss,
    epipolar_disparity_loss,
    finite_masked_mean,
    gradient_loss,
    lower_bound_penalty,
)
from .composite import LossBreakdown, LossWeights, combine_loss_terms
from .measurement import measurement_consistency_loss, sample_hr_at_lr_centers
from .metric_stereo_video import (
    MetricStereoVideoLoss,
    MetricStereoVideoLossBreakdown,
    MetricStereoVideoLossWeights,
    combine_metric_stereo_video_losses,
    depth_from_inverse_depth_m_inv,
    disparity_from_inverse_depth_m_inv,
    inverse_depth_scale_alignment_loss,
    laplace_inverse_depth_uncertainty_loss,
    left_right_consistency_loss,
    metric_factor_px_m,
    metric_stereo_video_loss,
    normalized_log_depth_loss,
    photometric_reprojection_loss,
    pose_residual_loss,
    robust_disparity_loss,
    robust_multiscale_disparity_loss,
    robust_multiscale_pixel_disparity_loss,
    scale_alignment_loss,
    stereo_reprojection_loss,
    temporal_reprojection_loss,
    validity_classification_loss,
    visibility_aware_temporal_residual_loss,
    warp_right_disparity_to_left,
)
from .temporal import temporal_consistency_loss, temporal_residual_consistency_loss
from .uncertainty import ffs_gate_regularizer, laplace_uncertainty_nll
from .validity import ValidityCompletionLoss, validity_completion_loss

__all__ = [
    "charbonnier",
    "disparity_loss",
    "epipolar_disparity_loss",
    "ffs_gate_regularizer",
    "finite_masked_mean",
    "gradient_loss",
    "lower_bound_penalty",
    "LossBreakdown",
    "LossWeights",
    "laplace_uncertainty_nll",
    "measurement_consistency_loss",
    "MetricStereoVideoLoss",
    "MetricStereoVideoLossBreakdown",
    "MetricStereoVideoLossWeights",
    "combine_metric_stereo_video_losses",
    "depth_from_inverse_depth_m_inv",
    "disparity_from_inverse_depth_m_inv",
    "inverse_depth_scale_alignment_loss",
    "laplace_inverse_depth_uncertainty_loss",
    "left_right_consistency_loss",
    "metric_factor_px_m",
    "metric_stereo_video_loss",
    "normalized_log_depth_loss",
    "photometric_reprojection_loss",
    "pose_residual_loss",
    "robust_disparity_loss",
    "robust_multiscale_disparity_loss",
    "robust_multiscale_pixel_disparity_loss",
    "scale_alignment_loss",
    "stereo_reprojection_loss",
    "temporal_reprojection_loss",
    "validity_classification_loss",
    "visibility_aware_temporal_residual_loss",
    "warp_right_disparity_to_left",
    "sample_hr_at_lr_centers",
    "temporal_consistency_loss",
    "temporal_residual_consistency_loss",
    "ValidityCompletionLoss",
    "validity_completion_loss",
    "combine_loss_terms",
]
