"""Evaluation metrics for disparity, temporal stability, and point clouds."""

from .boundary import boundary_epe, disparity_boundary_mask
from .disparity import (
    CompletenessImprovementReport,
    DisparityMetricReport,
    MetricResult,
    OutputValidityReport,
    bad_n,
    bad_pixel_rate,
    disparity_metrics,
    end_point_error,
    epe,
    invalid_negative_nan_rate,
    invalid_region_completeness,
    invalid_region_completeness_improvement,
    low_confidence_region_epe,
    output_validity_metrics,
)
from .pointcloud import (
    PointCloudExportResult,
    PointCloudResult,
    disparity_to_point_cloud,
    export_colored_point_cloud_ply,
    point_to_plane_error,
)
from .temporal import (
    TrustedRegionDegradationReport,
    legacy_temporal_disparity_error,
    temporal_disparity_error,
    temporal_residual_error,
    trusted_region_degradation,
)
from .spring_arms import (
    aggregate_metric_rows as aggregate_spring_metric_rows,
    disparity_metrics as spring_disparity_metrics,
    temporal_residual_metrics as spring_temporal_residual_metrics,
    topk_diagnostics as spring_topk_diagnostics,
)
from .metric_stereo_video import (
    AccuracyCoverageHistogram,
    MetricAccumulator as MetricStereoVideoAccumulator,
    MetricValue as MetricStereoVideoValue,
    endpoint_metric_values,
    scalar_metric,
    temporal_residual_metric_values,
)

__all__ = [
    "CompletenessImprovementReport",
    "DisparityMetricReport",
    "MetricResult",
    "OutputValidityReport",
    "PointCloudExportResult",
    "PointCloudResult",
    "TrustedRegionDegradationReport",
    "bad_n",
    "bad_pixel_rate",
    "boundary_epe",
    "disparity_boundary_mask",
    "disparity_metrics",
    "disparity_to_point_cloud",
    "end_point_error",
    "epe",
    "export_colored_point_cloud_ply",
    "invalid_negative_nan_rate",
    "invalid_region_completeness",
    "invalid_region_completeness_improvement",
    "low_confidence_region_epe",
    "legacy_temporal_disparity_error",
    "output_validity_metrics",
    "point_to_plane_error",
    "temporal_disparity_error",
    "temporal_residual_error",
    "trusted_region_degradation",
    "aggregate_spring_metric_rows",
    "spring_disparity_metrics",
    "spring_temporal_residual_metrics",
    "spring_topk_diagnostics",
    "AccuracyCoverageHistogram",
    "MetricStereoVideoAccumulator",
    "MetricStereoVideoValue",
    "endpoint_metric_values",
    "scalar_metric",
    "temporal_residual_metric_values",
]
